### ISSUE TITLE
dependency specifications

### ISSUE THREAD

**Issue by bnewbold** [Dogeek/fastapi_rss#2]
`fastapi-rss` looks cool, thanks for creating it!

I am curious whether the dependency versions are defined strictly on purpose, and if so why. For FastAPI, the specification is:

```fastapi = "^0.73.0"```

which I believe means anything greater than 0.73 but less than 0.74. I tried adding this package to a `pipenv`-based project just now, which was using FastAPI 0.75, and it resulted in either a downgrade, or impossible-to-resolve dependencies if I try to force `fastapi>=0.75.0`.

Here is a link to the poetry "caret requirements" docs: <https://python-poetry.org/docs/dependency-specification/#caret-requirements>

Is there a specific dependency on FastAPI internals which requires this tight coupling?

**Comment by sbordeyne** [comment]
Hello,

No there is no strict requirements for fastapi 0.73.0, I juste wrote the
library a while ago, and haven't checked if the library is still compatible
with the latest version of fastapi.

Will upgrade the package to update the requirements.

**Comment by bnewbold** [comment]
That would be great, thanks! Let me know if I can help (eg, with a PR).

Best would be the ability to upgrade `fastapi` in the future without worry that that `fastapi-rss` will have a conflicting dependency, and without `fastapi-rss` needing to update dependencies every time.

A new version of `fastapi-rss` would probably need to get pushed to pypi.org.

**Comment by bnewbold** [comment]
FWIW, I was able to work around this by locking `fastapi-rss` to the older version `0.1.3`, which does not specify a specific `fastapi` version: https://github.com/internetarchive/fatcat-scholar/commit/511c91ee94cc98f7dce0d563c1709f3c96de27e9

This allowed us to launch search result RSS feeds on https://scholar.archive.org

**Comment by sbordeyne** [comment]
Hello, I've upgraded the dependency to FastAPI to the latest available version. I've intentionally locked the version so that FastAPI v 1.0.0 and above will not work, in case tiangolo decides to push breaking changes to the library's internals. When the time comes, I'll upgrade this library and go for a new major release.

Thanks for your contributions
