### ISSUE TITLE
`RSSFeed` model ImportError when locale not set

### ISSUE THREAD

**Issue by sneakers-the-rat** [Dogeek/fastapi_rss#8]
`locale.getdefaultlocale()` (which is deprecated) and `locale.getlocale()` can return `None` if language cannot be determined: https://docs.python.org/3/library/locale.html#locale.getdefaultlocale

Since the default in the model calls the function directly (rather than using `default_factory`), the model can't be imported at all: https://github.com/sbordeyne/fastapi_rss/blob/558151c3503d408abdc711e9aee8f39c60a2a011/fastapi_rss/models/feed.py#L23

due to a predictable `AttributeError`: `NoneType` object has no attribute `lower` thrown here: https://github.com/sbordeyne/fastapi_rss/blob/558151c3503d408abdc711e9aee8f39c60a2a011/fastapi_rss/utils.py#L14

to fix: 
- use `default_factory` so the model can be imported and patched if needed
- make language optional, and check for `None` type in `get_locale_code`

**Comment by sbordeyne** [comment]
This has been deployed on PyPI
