### ISSUE TITLE
Maintenance Status?

### ISSUE THREAD

**Issue by sneakers-the-rat** [Dogeek/fastapi_rss#9]
Hello! Thanks for your work on this. It looks like development has gone dormant. I'd love to pitch in since i'm making a FastAPI RSS feed service rn. I can PR if you want to still manage the project, or else i'd be happy to take it over if you're finished with it!

**Comment by sbordeyne** [comment]
Hi, yeah feel free to make pull requests on it, it's pretty much stable now and compliant with the rss specs hence why development has gone dormant. I'll review pull requests as they arrive.

**Comment by sneakers-the-rat** [comment]
gr8 thank you for the quick reply :), just wanted to check before making PRs. Some minor maintenance things and maybe some QoL for implementing metadata for scholarly publication feeds on https://github.com/sneakers-the-rat/journal-rss , so shouldn't be controversial/complicated <3

**Comment by sbordeyne** [comment]
As long as the new features do not conflict with the official w3c spec for RSS 2.0, it's okay in my books. Some third parties do add extra features to RSS, or even change the metadatas significantly, but the goal is to remain compliant first, other vendor support should be under a feature flag / param / config option for that use case specifically.
